export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_FAILS = "PRODUCT_LIST_FAILS";
export const PRODCUT_LIST_SUCCESS = "PRODCUT_LIST_SUCCESS";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_FAILS = "PRODUCT_DETAILS_FAILS";
export const PRODCUT_DETAILS_SUCCESS = "PRODCUT_DETAILS_SUCCESS";
